### ISSUE TITLE
Inability to move and shoot at the same time

### ISSUE THREAD

**Issue by MajidAliKhanQuaid** [alisajidcs/space-invaders#1]
I'm trying to move and shoot but unable to do so, please fix the issue asap

**Comment by alisajidcs** [comment]
![ezgif-2-b35794bbf9](https://github.com/alisajidcs/space-invaders/assets/24201994/c39eb7e8-7cdf-408c-96b0-9bc745b0b99c)

As you can see in this video. you can move and shoot. So our team is closing this issue because we can't reproduce it.
